name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Core Layout's Tests
      run: xcodebuild -project CoreLayoutExample.xcodeproj -scheme CoreLayoutExample -destination 'platform=iOS Simulator,name=iPhone 16' test
